### ISSUE TITLE
Add More Questions to the Quiz Game

### ISSUE THREAD

**Issue by Bluebloodfr** [Bluebloodfr/Quiz_Game-LMGiraud-CDOF5#1]
## Description
Our quiz currently has a limited number of questions. To keep it fresh and engaging, we're looking to add more. This is a great first issue for new contributors!

## Tasks
- [x] Identify topics for new questions.
- [x] Write new questions and answers in the format used in the game.
- [x] Update the `questions` list in the `main.py` file.

## Acceptance Criteria
- Questions must be unique and not duplicates of existing ones.
- The language and grammar should be checked and correct.
- Questions should cover a variety of topics.
