### ISSUE TITLE
Refactor Code for Testability

### ISSUE THREAD

**Issue by Bluebloodfr** [Bluebloodfr/Quiz_Game-LMGiraud-CDOF5#3]
## Description
As our project grows, the need for tests becomes more evident. We need to refactor our code to make it more testable and maintainable.

## Tasks
- [ ] Identify code that is difficult to test.
- [ ] Refactor this code to be more modular and testable.
- [ ] Write unit tests for the new modules.

## Acceptance Criteria
- The refactored code should have clear, separate modules.
- Unit tests should cover at least 80% of the new modules' functionality.
- The game should still run as expected after the refactoring.
